export const cardArrayAlpha = [
  {
    serialNumber: 'a-001',
    cardName: 'Common Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 20,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-002',
    cardName: 'Uncommon Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 120,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 25,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-003',
    cardName: 'Rare Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 30,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-004',
    cardName: 'Rare holo Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 35,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-005',
    cardName: 'Mega rare Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 180,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 40,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-006',
    cardName: 'Mega rare holo Alpha Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 200,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 50,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'a-007',
    cardName: 'Common Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    backgroundColour: 'WHITE',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-008',
    cardName: 'Uncommon Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-009',
    cardName: 'Rare Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-010',
    cardName: 'Rare holo Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    backgroundColour: 'YELLOW',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-011',
    cardName: 'Mega rare Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-012',
    cardName: 'Mega rare holo Alpha Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'a-013',
    cardName: 'Common Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-014',
    cardName: 'Uncommon Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-015',
    cardName: 'Rare Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-016',
    cardName: 'Rare holo Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-017',
    cardName: 'Mega rare Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-018',
    cardName: 'Mega rare holo Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'a-019',
    cardName: 'Ultimate Alpha Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 110,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
];

export const cardArrayBeta = [
  {
    serialNumber: 'b-001',
    cardName: 'Common Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 20,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-002',
    cardName: 'Uncommon Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 120,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 25,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-003',
    cardName: 'Rare Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 30,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-004',
    cardName: 'Rare holo Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 35,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-005',
    cardName: 'Mega rare Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 180,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 40,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-006',
    cardName: 'Mega rare holo Beta Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 200,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 50,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'b-007',
    cardName: 'Common Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
    backgroundColour: 'WHITE',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-008',
    cardName: 'Uncommon Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-009',
    cardName: 'Rare Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-010',
    cardName: 'Rare holo Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png',
    backgroundColour: 'YELLOW',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-011',
    cardName: 'Mega rare Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-012',
    cardName: 'Mega rare holo Beta Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Retrieve Effect',
          statName: 'Omega Wink',
          itemEffectType: 'RETRIEVE',
        },
      ],
    },
  },
  {
    serialNumber: 'b-013',
    cardName: 'Common Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-014',
    cardName: 'Uncommon Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-015',
    cardName: 'Rare Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-016',
    cardName: 'Rare holo Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-017',
    cardName: 'Mega rare Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-018',
    cardName: 'Mega rare holo Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
  {
    serialNumber: 'b-019',
    cardName: 'Ultimate Beta Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 110,
          description: 'Strength Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'STRENGTH',
        },
      ],
    },
  },
];

export const cardArrayGamma = [
  {
    serialNumber: 'g-001',
    cardName: 'Common Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 20,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-002',
    cardName: 'Uncommon Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 120,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 25,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-003',
    cardName: 'Rare Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 30,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-004',
    cardName: 'Rare holo Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 150,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 35,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-005',
    cardName: 'Mega rare Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 180,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 40,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-006',
    cardName: 'Mega rare holo Gamma Monster card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 200,
          description: 'Health',
          statName: 'Omega Wink',
          monsterEffectType: 'HEALTH',
        },
        {
          value: 50,
          description: 'Attack',
          statName: 'Omega Wink',
          monsterEffectType: 'ATTACK',
        },
      ],
    },
  },
  {
    serialNumber: 'g-007',
    cardName: 'Common Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    backgroundColour: 'WHITE',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-008',
    cardName: 'Uncommon Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-009',
    cardName: 'Rare Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-010',
    cardName: 'Rare holo Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    backgroundColour: 'YELLOW',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-011',
    cardName: 'Mega rare Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
    backgroundColour: 'PURPLE',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-012',
    cardName: 'Mega rare holo Gamma Item card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Draw Effect',
          statName: 'Omega Wink',
          itemEffectType: 'DRAW',
        },
      ],
    },
  },
  {
    serialNumber: 'g-013',
    cardName: 'Common Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    backgroundColour: 'BLACK',
    cardStats: {
      create: [
        {
          value: 50,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-014',
    cardName: 'Uncommon Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 60,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-015',
    cardName: 'Rare Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png',
    backgroundColour: 'BLUE',
    cardStats: {
      create: [
        {
          value: 70,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-016',
    cardName: 'Rare holo Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 80,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-017',
    cardName: 'Mega rare Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
    backgroundColour: 'GREEN',
    cardStats: {
      create: [
        {
          value: 90,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-018',
    cardName: 'Mega rare holo Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 100,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
  {
    serialNumber: 'g-019',
    cardName: 'Ultimate Gamma Powerup card test 1',
    description: 'This card has power and magic infused with a hint of safron.',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png',
    backgroundColour: 'RED',
    cardStats: {
      create: [
        {
          value: 110,
          description: 'Health Effect',
          statName: 'Dark Elixar',
          powerUpEffectType: 'HEALTH',
        },
      ],
    },
  },
];

export const users = [
  { email: 'xtombrock1989@gmail.com', username: 'xtombrock', id: 'test' },
  { email: 'testuser@example.com', username: 'testy', id: 'test1' },
  { email: 'testuser3@example.com', username: 'manny' },
  { email: 'testuser4@example.com', username: 'welshy' },
  { email: 'testuser5@example.com', username: 'geolorald' },
  { email: 'testuser6@example.com', username: 'examplenme' },
  { email: 'testuser7@example.com', username: 'trasds' },
  { email: 'testuser8@example.com', username: 'jason1' },
  { email: 'testuser9@example.com', username: 'problemman' },
  { email: 'testuser10@example.com', username: 'revenge1' },
  { email: 'testuser11@example.com', username: 'trever1' },
  { email: 'testuser12@example.com', username: 'outliners' },
  { email: 'testuser130@example.com', username: 'funding55' },
  { email: 'testuser14@example.com', username: 'fouteen' },
  { email: 'testuser15@example.com', username: 'traveller2' },
  { email: 'testuser16@example.com', username: 'crowners' },
  { email: 'testuser17@example.com', username: 'seveteenn5' },
  { email: 'testuser18@example.com', username: 'previous88' },
  { email: 'testuser19@example.com', username: 'tester9' },
  { email: 'testuser20@example.com', username: 'twnty20' },
  { email: 'testuser21@example.com', username: 'twoonetwooonw' },
  {
    email: 'admin@admin.com',
    username: 'adminCraig',
    role: 'ADMIN',
    id: 'admin',
  },
  { email: 'dev@dev.com', username: 'deve', role: 'DEVELOPER', id: 'dev' },
];
