export const cards = [
  {
    serialNumber: 'a-001',
    cardName: 'Common Alpha Monster card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    backgroundColour: 'BLUE',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 100,
      attack: 20,
    },
  },
  {
    serialNumber: 'a-002',
    cardName: 'Uncommon Alpha Monster card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 120,
      attack: 25,
    },
  },
  {
    serialNumber: 'a-003',
    cardName: 'Rare Alpha Monster card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 150,
      attack: 30,
    },
  },
  {
    serialNumber: 'a-004',
    cardName: 'Rare holo Alpha Monster card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 150,
      attack: 35,
    },
  },
  {
    serialNumber: 'a-005',
    cardName: 'Mega rare Alpha Monster card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 180,
      attack: 40,
    },
  },
  {
    serialNumber: 'a-006',
    cardName: 'Mega rare holo Alpha Monster card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    backgroundColour: 'RED',
    monsterDetail: {
      monsterClass: 'ELEMENTAL',
      health: 200,
      attack: 50,
    },
  },
  {
    serialNumber: 'a-007',
    cardName: 'Common Alpha Item card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    backgroundColour: 'WHITE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'a-008',
    cardName: 'Uncommon Alpha Item card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
    backgroundColour: 'BLUE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'a-009',
    cardName: 'Rare Alpha Item card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'a-010',
    cardName: 'Rare holo Alpha Item card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    backgroundColour: 'YELLOW',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'a-011',
    cardName: 'Mega rare Alpha Item card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'a-012',
    cardName: 'Mega rare holo Alpha Item card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
    backgroundColour: 'BLACK',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'a-013',
    cardName: 'Common Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    backgroundColour: 'BLACK',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'a-014',
    cardName: 'Uncommon Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'a-015',
    cardName: 'Rare Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'a-016',
    cardName: 'Rare holo Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'a-017',
    cardName: 'Mega rare Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
    backgroundColour: 'GREEN',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'a-018',
    cardName: 'Mega rare holo Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'a-019',
    cardName: 'Ultimate Alpha Powerup card test 1',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'ALPHA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 110,
    },
  },
  {
    serialNumber: 'b-001',
    cardName: 'Common Beta Monster card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png',
    backgroundColour: 'BLUE',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 100,
      attack: 20,
    },
  },
  {
    serialNumber: 'b-002',
    cardName: 'Uncommon Beta Monster card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 120,
      attack: 25,
    },
  },
  {
    serialNumber: 'b-003',
    cardName: 'Rare Beta Monster card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 150,
      attack: 30,
    },
  },
  {
    serialNumber: 'b-004',
    cardName: 'Rare holo Beta Monster card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 150,
      attack: 35,
    },
  },
  {
    serialNumber: 'b-005',
    cardName: 'Mega rare Beta Monster card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 180,
      attack: 40,
    },
  },
  {
    serialNumber: 'b-006',
    cardName: 'Mega rare holo Beta Monster card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png',
    backgroundColour: 'RED',
    monsterDetail: {
      monsterClass: 'DEMONIC',
      health: 200,
      attack: 50,
    },
  },
  {
    serialNumber: 'b-007',
    cardName: 'Common Beta Item card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
    backgroundColour: 'WHITE',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'b-008',
    cardName: 'Uncommon Beta Item card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png',
    backgroundColour: 'BLUE',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'b-009',
    cardName: 'Rare Beta Item card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'b-010',
    cardName: 'Rare holo Beta Item card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png',
    backgroundColour: 'YELLOW',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'b-011',
    cardName: 'Mega rare Beta Item card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'b-012',
    cardName: 'Mega rare holo Beta Item card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png',
    backgroundColour: 'BLACK',
    itemDetail: {
      effectType: 'RETRIEVE',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'b-013',
    cardName: 'Common Beta Powerup card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png',
    backgroundColour: 'BLACK',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'b-014',
    cardName: 'Uncommon Beta Powerup card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'b-015',
    cardName: 'Rare Beta Powerup card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'b-016',
    cardName: 'Rare holo Beta Powerup card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'b-017',
    cardName: 'Mega rare Beta Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
    backgroundColour: 'GREEN',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'b-018',
    cardName: 'Mega rare holo Beta Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'b-019',
    cardName: 'Ultimate Beta Powerup card test 1',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'BETA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'STRENGTH',
      effectValue: 110,
    },
  },
  {
    serialNumber: 'g-001',
    cardName: 'Common Gamma Monster card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    backgroundColour: 'BLUE',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 100,
      attack: 20,
    },
  },
  {
    serialNumber: 'g-002',
    cardName: 'Uncommon Gamma Monster card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 120,
      attack: 25,
    },
  },
  {
    serialNumber: 'g-003',
    cardName: 'Rare Gamma Monster card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 150,
      attack: 30,
    },
  },
  {
    serialNumber: 'g-004',
    cardName: 'Rare holo Gamma Monster card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 150,
      attack: 35,
    },
  },
  {
    serialNumber: 'g-005',
    cardName: 'Mega rare Gamma Monster card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    backgroundColour: 'GREEN',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 180,
      attack: 40,
    },
  },
  {
    serialNumber: 'g-006',
    cardName: 'Mega rare holo Gamma Monster card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'MONSTER',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    backgroundColour: 'RED',
    monsterDetail: {
      monsterClass: 'TREE',
      health: 200,
      attack: 50,
    },
  },
  {
    serialNumber: 'g-007',
    cardName: 'Common Gamma Item card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    backgroundColour: 'WHITE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'g-008',
    cardName: 'Uncommon Gamma Item card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
    backgroundColour: 'BLUE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'g-009',
    cardName: 'Rare Gamma Item card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'g-010',
    cardName: 'Rare holo Gamma Item card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    backgroundColour: 'YELLOW',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'g-011',
    cardName: 'Mega rare Gamma Item card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
    backgroundColour: 'PURPLE',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'g-012',
    cardName: 'Mega rare holo Gamma Item card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'ITEM',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
    backgroundColour: 'BLACK',
    itemDetail: {
      effectType: 'DRAW',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'g-013',
    cardName: 'Common Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'COMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    backgroundColour: 'BLACK',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 50,
    },
  },
  {
    serialNumber: 'g-014',
    cardName: 'Uncommon Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'UNCOMMON',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 60,
    },
  },
  {
    serialNumber: 'g-015',
    cardName: 'Rare Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'RARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png',
    backgroundColour: 'BLUE',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 70,
    },
  },
  {
    serialNumber: 'g-016',
    cardName: 'Rare holo Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'RAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 80,
    },
  },
  {
    serialNumber: 'g-017',
    cardName: 'Mega rare Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARARE',
    holographic: false,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png',
    backgroundColour: 'GREEN',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 90,
    },
  },
  {
    serialNumber: 'g-018',
    cardName: 'Mega rare holo Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'MEGARAREHOLO',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 100,
    },
  },
  {
    serialNumber: 'g-019',
    cardName: 'Ultimate Gamma Powerup card test 1',
    edition: 'first',
    rarity: 'ULTIMATE',
    holographic: true,
    packType: 'GAMMA',
    cardType: 'POWERUP',
    imageUrl: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png',
    backgroundColour: 'RED',
    powerUpDetail: {
      effectType: 'HEALTH',
      effectValue: 110,
    },
  },
];

export const users = [
    { email: 'xtombrock1989@gmail.com', username: 'xtombrock', id: 'test' },
    { email: 'testuser@example.com', username: 'testy' },
    { email: 'testuser3@example.com', username: 'manny' },
    { email: 'testuser4@example.com', username: 'welshy' },
    { email: 'testuser5@example.com', username: 'geolorald' },
    { email: 'testuser6@example.com', username: 'examplenme' },
    { email: 'testuser7@example.com', username: 'trasds' },
    { email: 'testuser8@example.com', username: 'jason1' },
    { email: 'testuser9@example.com', username: 'problemman' },
    { email: 'testuser10@example.com', username: 'revenge1' },
    { email: 'testuser11@example.com', username: 'trever1' },
    { email: 'testuser12@example.com', username: 'outliners' },
    { email: 'testuser130@example.com', username: 'funding55' },
    { email: 'testuser14@example.com', username: 'fouteen' },
    { email: 'testuser15@example.com', username: 'traveller2' },
    { email: 'testuser16@example.com', username: 'crowners' },
    { email: 'testuser17@example.com', username: 'seveteenn5' },
    { email: 'testuser18@example.com', username: 'previous88' },
    { email: 'testuser19@example.com', username: 'tester9' },
    { email: 'testuser20@example.com', username: 'twnty20' },
    { email: 'testuser21@example.com', username: 'twoonetwooonw' },
    {
      email: 'admin@admin.com',
      username: 'adminCraig',
      role: 'ADMIN',
      id: 'admin',
    },
    { email: 'dev@dev.com', username: 'deve', role: 'DEVELOPER', id: 'dev' },
  ];
